using Godot;

namespace Urman.Godot;

/// <summary>
/// Plays the synthetic PREVIEW voice lines of the Act I prologue.
/// A clip is found by text id: <c>voice_preview/&lt;short-id&gt;[.lvl-some|.lvl-fluent].wav</c>,
/// mirroring how the content pack resolves the language-level text variant. A line
/// without a file simply stays silent, so captions keep working on their own.
/// The clips are generated by tools/voice/gemini_tts and are not final recordings.
/// </summary>
internal static class PrologueVoice
{
    private const string Dir = "res://assets/audio/act1/voice_preview/";
    private const string TextPrefix = "urman.chapter1:text/";
    private static AudioStreamPlayer? _player;

    /// <summary>Plays the clip of a content text id; returns its length in seconds (0 = none).</summary>
    public static double PlayText(Node host, string textId, string languageLevel)
    {
        var shortId = textId.StartsWith(TextPrefix, System.StringComparison.Ordinal) ? textId[TextPrefix.Length..] : textId;
        if (languageLevel is "some" or "fluent" && Exists($"{shortId}.lvl-{languageLevel}"))
            return PlayClip(host, $"{shortId}.lvl-{languageLevel}");
        return PlayClip(host, shortId);
    }

    /// <summary>Plays a clip by file id; returns its length in seconds (0 = none).</summary>
    public static double PlayClip(Node host, string clipId)
    {
        Stop();
        if (!Exists(clipId) || host.GetTree() is not { } tree) return 0;
        var stream = ResourceLoader.Load<AudioStream>(Dir + clipId + ".wav");
        if (stream is null) return 0;
        if (_player is null || !GodotObject.IsInstanceValid(_player))
        {
            _player = new AudioStreamPlayer { Name = "PrologueVoice", Bus = AudioSettingsService.VoiceBus, VolumeDb = -2f };
            tree.Root.AddChild(_player);
        }
        _player.Stream = stream;
        _player.Play();
        return stream.GetLength();
    }

    /// <summary>
    /// Plays a clip from a point in the world (a voice calling from among the trees);
    /// returns its length in seconds (0 = none). It frees itself and, unlike
    /// <see cref="PlayClip"/>, does not cut off the speaking voice.
    /// </summary>
    public static double PlayAt(Node host, Vector3 globalPosition, string clipId, float volumeDb = 0f, float maxDistance = 70f)
    {
        if (!Exists(clipId) || !host.IsInsideTree() || ResourceLoader.Load<AudioStream>(Dir + clipId + ".wav") is not { } stream) return 0;
        var player = new AudioStreamPlayer3D
        {
            Name = "PrologueVoiceAt_" + clipId,
            Stream = stream,
            Bus = AudioSettingsService.VoiceBus,
            VolumeDb = volumeDb,
            MaxDistance = maxDistance,
            UnitSize = 14f
        };
        host.AddChild(player);
        player.GlobalPosition = globalPosition;
        player.Finished += () => player.QueueFree();
        player.Play();
        return stream.GetLength();
    }

    public static void Stop()
    {
        if (_player is not null && GodotObject.IsInstanceValid(_player)) _player.Stop();
    }

    private static bool Exists(string clipId) => ResourceLoader.Exists(Dir + clipId + ".wav");
}
