import type { JsonValue, TransactionPlan } from '../contracts/runtime-contracts.mjs';
export const QuestStatus: Readonly<{ Active: 'active'; Completed: 'completed'; Failed: 'failed'; Cancelled: 'cancelled' }>;
export const ObjectiveStatus: Readonly<{ Pending: 'pending'; Active: 'active'; Completed: 'completed'; Failed: 'failed' }>;
export interface QuestInstanceState {
  readonly questId: string; readonly questInstanceId: string; readonly status: 'active' | 'completed' | 'failed' | 'cancelled'; readonly attempt: number; readonly stageIndex: number;
  readonly objectives: JsonValue; readonly generatedBindings: JsonValue; readonly capabilitySnapshots: JsonValue; readonly activeCapabilities: JsonValue; readonly checkpoint: JsonValue; readonly originCheckpoint: JsonValue;
}
export interface CapabilityRequest { readonly capabilityInstanceId: string; readonly protocolId: string; readonly exactVersion: string; readonly configRef: string; readonly config: JsonValue; readonly outcomeSchemaRef: string }
export function questObjectiveOccurrenceId(input: { readonly questInstanceId: string; readonly stageId: string; readonly objectiveId: string; readonly triggerId: string }): string;
export function createQuestInstance(definition: JsonValue, options: { readonly questInstanceId: string; readonly generatedBindings?: JsonValue; readonly evaluateCondition?: (condition: JsonValue, context: JsonValue) => boolean; readonly evaluationContext?: JsonValue; readonly configResolver?: (configRef: string) => JsonValue }): QuestInstanceState;
export function createQuestRun(definition: JsonValue, options: { readonly questInstanceId: string; readonly generatedBindings?: JsonValue; readonly evaluateCondition?: (condition: JsonValue, context: JsonValue) => boolean; readonly evaluationContext?: JsonValue; readonly configResolver?: (configRef: string) => JsonValue }): { readonly instance: QuestInstanceState; readonly capabilityRequests: readonly CapabilityRequest[] };
export function reduceQuestLifecycle(options: { readonly definition: JsonValue; readonly instance: QuestInstanceState; readonly command: JsonValue; readonly stateKey: string; readonly evaluateCondition?: (condition: JsonValue, context: JsonValue) => boolean; readonly planEffects?: (effects: readonly JsonValue[], context: JsonValue) => Pick<TransactionPlan, 'effects' | 'events' | 'claims'>; readonly configResolver?: (configRef: string) => JsonValue; readonly evaluationContext?: JsonValue; readonly cleanupPlan?: Pick<TransactionPlan, 'releaseClaimOwnerIds' | 'releaseClaimLifecycleScopes'>; readonly capabilityLifecycle?: { prepareCleanup(input: { readonly capabilityInstanceIds: readonly string[]; readonly reason: string }): Pick<TransactionPlan, 'releaseClaimOwnerIds' | 'releaseClaimLifecycleScopes'> } }): { readonly nextState: QuestInstanceState; readonly capabilityRequests: readonly CapabilityRequest[]; readonly capabilityCleanups: readonly { readonly capabilityInstanceIds: readonly string[]; readonly reason: string; readonly releaseClaimOwnerIds: readonly string[]; readonly releaseClaimLifecycleScopes: readonly string[] }[]; readonly plan: TransactionPlan };
